### ISSUE TITLE
 events.js:141 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by MarcW1g** [Kevin-De-Koninck/Apple-Homekit-and-PiHole-server#1]
Hello, 
When I run this program with: 
sudo node Core.js

I get the error message:
HAP-NodeJS starting...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventedHTTPServer.listen (/home/pi/HAP-NodeJS/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/home/pi/HAP-NodeJS/lib/HAPServer.js:158:20)
    at Accessory.publish (/home/pi/HAP-NodeJS/lib/Accessory.js:509:16)
    at /home/pi/HAP-NodeJS/Core.js:32:13

What should I do with this?

**Comment by Kevin-De-Koninck** [comment]
Hello,
I thought I had a development brach, but instead was working in the master branch... This is currently in development (my apologies). I fixed this and now have a development branch. The master branch now only contains code that I've tested on a clean raspberry pi.

Try to download the files again (if you're testing the onboard light):
```bash
sudo rm -f ~/HAP-NodeJS/accessories/Light_OnBoardLED_accessory.js
sudo rm -f ~/HAP-NodeJS/python/onboard-LED.py

cd ~/HAP-NodeJS/accessories/
sudo wget https://raw.githubusercontent.com/Kevin-De-Koninck/Apple-Homekit-and-PiHole-server/master/accessories/Light_OnBoardLED_accessory.js

cd ~/HAP-NodeJS/python
sudo wget https://raw.githubusercontent.com/Kevin-De-Koninck/Apple-Homekit-and-PiHole-server/master/python%20scripts/onboard-LED.py
```

then try to start Core.js again.

I had a couple of errors in those scripts (changed them without testing) but I just tested everything that's in the readme file of the master branch and it's working for me.

**Comment by MarcW1g** [comment]
It works after the update! Thanks!
